{% set build = 0 %}
{% set commit = "6235e6907526d468e2c35f14c38db1e308698bc9" %}

package:
  name: dynare-preprocessor
  version: 0.0.0.dev{{ build }}.{{ commit }}

source:
  url: https://git.dynare.org/Dynare/preprocessor/-/archive/{{ commit }}/preprocessor.tar.gz
  sha256: 06f76245ff5c6ac0811438cea6b817a321dc702c188b680e2a3191b54837c4ab

build:
  number: {{ build }}
  skip: true  # [win or osx]

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - meson
    - bison
    - flex
    - pkg-config
  host:
    - libboost-headers
    - pthread-stubs

test:
  files:
    - example1.mod

about:
  home: https://www.dynare.org/
  summary: Dynare preprocessor
  description: Preprocessor for Dynare, a platform for handling a wide class of economic models.
  doc_url: https://www.dynare.org/manual/
  dev_url: https://git.dynare.org/Dynare/preprocessor
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING

extra:
  recipe-maintainers:
    - albop
    - svillemot
